version: '3'
services:
  app:
    build: .
    container_name: app
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_ENV: production
    depends_on:
      - db
  redis2:
    image: redis:latest
    container_name: redis2
    ports:
      - '6379:6379'
    expose:
      - '6379'
    networks:
      - redis
networks:
  redis:
    driver: bridge
